### PR TITLE
Updated AutoCodepage plugin to version 1.2.2

### PR DESCRIPTION
**Pull request by dinkumoil**

### CODE REVIEW

**Comment by dinkumoil** [comment]
Remark for the maintainer (@chcg I guess):

In the file `plugins64.xml` I forgot to add the following line (provided that it is supported by 64 bit plugin manager):

`<minVersion>7.5.7</minVersion>`

Would you please add it? Or is it necessary to make a new PR?

**Comment by chcg** [comment]
@dinkumoil I could add the min version info, should this be also added for the 32bit version?

**Comment by dinkumoil** [comment]
@chcg Thank you!

I don't see the update of my plugin in 32 bit PluginManager's development plugin list, maybe it's caused by the certificate error at https://bruderste.in, maybe it has another reason. I want to avoid that the update is invisible because of the min version info, so I leave it away at the moment.  I will add the min version info to the 32 bit version by myself after I have seen it in PluginManager's development plugin list.

**Comment by dinkumoil** [comment]
@chcg Since the cert error on https://bruderste.in is resolved the 32 bit development plugin list now shows the updated version of my plugin. So I've added the `minVersionInfo` tag to the XML data. If you want you can add it also to the XML data of the 64 bit plugin list. Otherwise I will make a new PR at Monday.

**Pull request merged**
