### PR TITLE
New md5 sum for SQLinForm new release 5.1.97

### PR DESCRIPTION
**Pull request by guidomarcel**

### CODE REVIEW

**Comment by guidomarcel** [comment]
the check has failed. Can you help me fix this? I do not know what is the error

Thanks
Guido

**Comment by chcg** [comment]
I think #37 is the relevant one and this one could be deleted.

**Comment by guidomarcel** [comment]
Yes. Thanks

 

Von: chcg [mailto:notifications@github.com] 
Gesendet: Sonntag, 1. Oktober 2017 23:00
An: bruderstein/npp-plugins-x64 <npp-plugins-x64@noreply.github.com>
Cc: guidomarcel <guido.thelen@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [bruderstein/npp-plugins-x64] New md5 sum for SQLinForm new release 5.1.97 (#35)

 

I think #37 <https://github.com/bruderstein/npp-plugins-x64/pull/37>  is the relevant one and this one could be deleted.

**Comment by guidomarcel** [comment]
this one can be deleted

**Pull request closed without merging**
