### PR TITLE
Add Poor Man's T-SQL Formatter (64-bit) plugin

### PR DESCRIPTION
**Pull request by TaoK**
Following the instructions at https://notepad-plus-plus.org/community/topic/13661/plugin-manager-x64-available-submit-your-plugins - let me know if I'm missing something!

### CODE REVIEW

**Comment by bruderstein** [comment]
@taok thanks! You need to add the `md5sum` hashes to the validate.json for each file copied with `validate="true"`

**Comment by TaoK** [comment]
@bruderstein: 

Argh, looks like I have a problem... the entries in validate.json are identified by filename without path (at least that's what it looks like for AutoCodepage), and I have two identical filenames - that vary only by path (source path in the ZIP file and destination path).

Should I just disable validation for one of those files??

Is there any reason we don't validate the download instead of validating the actual destination files? I thought that was how the old one worked (at least that's what the admin UI, which I just saw for the first time in a few years, seems to imply is happening).

**Comment by TaoK** [comment]
(note to self: getting MD5 hash seems straightforward with Get-FileHash -Path .\somefile.dll -Algorithm MD5, and matches the results in validate.json except for uppercase vs lowercase)

**Comment by bruderstein** [comment]
@TaoK the filename in the JSON isn't actually too important (it's there to aid a future migration) - you're welcome to put the path name in there (might be easiest to separate with `/` rather than `\`)

The plugin manager has always (in every version) validated the actual DLL file being copied. In the 32bit admin system, when you enter the URL, it asks if it should download the files. When you click yes, the files are shown on the right with a small "Add Hash" link. This adds the hash of that file to the list of valid files.

This came up recently, so the reasons for doing it this way are explained here: https://github.com/bruderstein/npp-plugins-x64/issues/27#issuecomment-325207228

**Comment by chcg** [comment]
Added the missing md5 hashes to the validate.json. Added also the missing hash values for dlls at https://npppm.bruderste.in/plugins/view/poor-mans-t-sql-formatter.

**Comment by TaoK** [comment]
Thanks very much @chcg !

**Pull request merged**
