### PR TITLE
Dave user patch 1

### PR DESCRIPTION
**Pull request by dave-user**
This patch adds Customize Toolbar 4.1 (64-bit) to the plugins64.xml and validate.json repository files.

### CODE REVIEW

**Comment by MAPJe71** [comment]
@dave-user any plans on making the source available on SourceForge or GitHub?

**Comment by dave-user** [comment]
Hi Menno,

No, I don’t have any plans to make the source available.

Why do you ask?

Regards,

Dave

**Comment by MAPJe71** [comment]
Short answer:
1. to be able to debug the plugin;
2. to add functionality;

Long answer:
1. I've run into a problem of custom buttons being disabled and moved to the right side of the toolbar on first startup of Notepad++. The custom buttons are for PythonScript scripts. It first occured after installing the DSpellCheck plugin (as part of N++ 7.5.3 distribution) and uninstalling the DSpellCheck plugin solves the problem or at least appears to.
Toolbar layout after startup of Notepad++:
capture-2017-07-20-21 14 482018-03-15-22 03 53
Toolbar layout after restart of Notepad++:
capture-2017-07-20-21 14 482018-03-15-22 04 27
Toolbar layout expected after startup or restart of Notepad++:
capture-2017-07-20-21 14 482018-03-15-22 05 13
FYI: running Notepad++ 7.5.5 32-bit on Windows 10 64-bit, to be able to use a different icon and name (in tooltip) I'm not using PythonScript plugin's configuration for toolbar icons.
2. I run both Notepad++ 32 and 64-bit that share their confguration in %APPDATA%. Some of the plugins I use in 32-bit N++ are not yet available in 64-bit N++ i.e. the TagsView, PythonScript and LocationNavigate plugins. The custom toolbar layout gets messed up when switching between 32 and 64-bit N++. Current workaround: making sure a N++ 32-bit is running before starting any 64-bit N++ and making sure all 64-bit N++'s are closed before closing the last 32-bit N++.

**Comment by dave-user** [comment]
Hi Menno,

1.  This is known issue due to Notepad++ start-up sequencing.  Plugin menu items are created after the Notepad++ menu items.  If this was easy to fix, it would have been fixed.
     You can change the icons for Notepad++ built-in commands and plugin commands using the Custom Buttons feature.

2. This is not something that Customize Toolbar was designed to handle.  I suspect the simplest solution would be to have separate CustomizeToolbar.dat files for 32-bit and 64-bit.

Regards,

Dave

**Comment by MAPJe71** [comment]
> This is known issue due to Notepad++ start-up sequencing. Plugin menu items are created after the Notepad++ menu items.

Okay but why are only 4 of the 15 custom buttons moved to the far right and disabled?

> You can change the icons for Notepad++ built-in commands and plugin commands using the Custom Buttons feature.

Yep, that's why I use the Customize Toolbar plugin.
ATM a total of 15 custom toolbar buttons in 32-bit N++, 7 for built-in commands, 7 for plugin commands, and 1 to replace the default image of the LuaScript plugin button.

> separate CustomizeToolbar.dat files for 32-bit and 64-bit

I guess that might work e.g. in N++ 32-bit something like:
```
    if CustomizeToolbar-32.dat available
        read CustomizeToolbar-32.dat
    else
        if CustomizeToolbar-32.btn available
            read CustomizeToolbar-32.btn
            write CustomizeToolbar-32.dat
        else
            if CustomizeToolbar.btn available
                read CustomizeToolbar.btn
                write CustomizeToolbar-32.dat
            else
                // examples of definitions
                write CustomizeToolbar-32.btn
                write CustomizeToolbar-32.dat
            end
        end
    end
```

**Comment by dave-user** [comment]
Hi Menno,

1)  Okay but why are only 4 of the 15 custom buttons moved to the far right and disabled?

Good question.  I will investigate.

2)  I guess that might work e.g. in N++ 32-bit something like ...

Actually, my plan was to change Customize Toolbar (64-bit) so that the files are called:  CustomizeToolbar64.btn  and CustomizeToolbar64.btn 

The 64-bit version would always read/write to these files, and the 32-bit version would always read/write to the un-suffixed files.

Or would that not work for you?

Regards,

Dave

**Comment by MAPJe71** [comment]
1. 👍  
2. Yep that would also work though I guess you ment CustomizeToolbar64.btn and CustomizeToolbar64.**dat** ;-)

**Pull request merged**
