### PR TITLE
added nppftp x64 version

### PR DESCRIPTION
**Pull request by chcg**

### CODE REVIEW

**Comment by chcg** [comment]
@bruderstein Could you check the travis issue. How is the expectation?

**Comment by bruderstein** [comment]
@chcg I think I might have fixed this in master (difficult to tell because it travis handles PRs differently). Can you try rebasing on current master?

**Comment by bruderstein** [comment]
Also, don't forget to add the `md5sum` of the DLL to the validate.json as you're copying with `validate="true"`

**Comment by bruderstein** [comment]
Seems to work now :+1:

And thanks for adding these, I think we can announce this now \o/

**Comment by chcg** [comment]
Almost, there is an issue with the path of the docs and validation seems to make problems.

**Comment by bruderstein** [comment]
Hmm... it validated for me...?

Which docs?

**Comment by chcg** [comment]
Should be 
`<copy from="bin64\*.txt" to="$PLUGINDIR$\doc\mimeTools"/>`
instead of
`<copy from="*.txt" to="$PLUGINDIR$\doc\mimeTools"/>`

**Comment by bruderstein** [comment]
oh... feel free to commit that directly to master :)

**Comment by chcg** [comment]
done

**Pull request merged**
