### PR TITLE
update SQLinForm to 5.3.16

### PR DESCRIPTION
**Pull request by guidomarcel**

### CODE REVIEW

**Comment by chcg** [comment]
@guidomarcel Would you like to provide a zip file for 5.3.19 x64 version? I have already prepared the remaining parts here for the x64 version.

I found two small issues on SQL Formatting Options. 
- The tab with the options could just be activated, but not deactivated. Is this intended?
- The icon in the tab bar has a black background. Visible with multiple plugins using it, like e.g. nppftp/snippets
grafik

**Comment by guidomarcel** [comment]
Hi,

will do so tomorrow.

Thanks

Guido

 

Von: chcg <notifications@github.com> 
Gesendet: Donnerstag, 11. Oktober 2018 08:53
An: bruderstein/npp-plugins-x64 <npp-plugins-x64@noreply.github.com>
Cc: guidomarcel <guido.thelen@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [bruderstein/npp-plugins-x64] update SQLinForm to 5.3.16 (#99)

 

@guidomarcel <https://github.com/guidomarcel>  Would you like to provide a zip file for 5.3.19 x64 version? I have already prepared the remaining parts here for the x64 version.

I found a small issue on SQL Formatting Options. They could just be activated, but not deactivated. Is this intended?

**Comment by guidomarcel** [comment]
Hi chcg,

zip file SQLinFormNpp64_5.3.19.zip is available. Which options cannot be deactivated?

 

Thanks

Guido

 

Von: chcg <notifications@github.com> 
Gesendet: Donnerstag, 11. Oktober 2018 08:53
An: bruderstein/npp-plugins-x64 <npp-plugins-x64@noreply.github.com>
Cc: guidomarcel <guido.thelen@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [bruderstein/npp-plugins-x64] update SQLinForm to 5.3.16 (#99)

 

@guidomarcel <https://github.com/guidomarcel>  Would you like to provide a zip file for 5.3.19 x64 version? I have already prepared the remaining parts here for the x64 version.

I found a small issue on SQL Formatting Options. They could just be activated, but not deactivated. Is this intended?

**Comment by chcg** [comment]
@guidomarcel With activating\deactivating I mean a toggling of the options window.

**Pull request merged**
