### PR TITLE
Update DSpellCheck to 1.4.13

### PR DESCRIPTION
**Pull request by Predelnik**

### CODE REVIEW

**Comment by chcg** [comment]
@Predelnik As PM itself is not really compatible with N++ newer than 7.6.x do you think it makes sense to add an update that requires N++ 7.7 ? Currently I have no clear opinion on that.

**Comment by Predelnik** [comment]
I haven't heard about that, probably it doesn't then. Why it's not compatible btw?

**Comment by chcg** [comment]
Mainly because a structural change to the xml would be required as the plugins since 7.6.x need to be placed into subdirs and the name of the subdir need to be constructed from the main plugin dll name.
So a new field need to be added and for 32bit the web interface would needed to be changed. This can't be done without the help of @bruderstein.
To my last knowledge he made the decision to stop working on PM as the builtin PA is available and splitting up the user base doesn't make sense. Just an official statement on that is still missing.

**Comment by Predelnik** [comment]
Thank you, that's understandable, I also found web interface for 32-bit unreachable yesterday. Let's close this PR then.

**Comment by chcg** [comment]
@Predelnik Web interface is accessible to me. Just the certificate is not updated by dave. I had to add a security exception for my browser to be able to use it.

**Comment by Predelnik** [comment]
Ah, looks like it was due to proxy/VPN I was using. Thanks for the info even if I don't have to update to new version there now I guess.

**Pull request closed without merging**
