### PR TITLE
updated nppcrypt in plugins64.xml to 1.0.1.5

### PR DESCRIPTION
**Pull request by jeanpaulrichter**

### CODE REVIEW

**Review by bruderstein — CHANGES_REQUESTED** [review]
You need to add the new md5 of `nppcrypt.dll` to validate.json too

**Comment by bruderstein** [comment]
You can just push the extra commit to this branch, no need to add a separate PR. It also simplifies the update, as both things are deployed together.

**Comment by bruderstein** [comment]
I'll merge them both this time though.

**Comment by jeanpaulrichter** [comment]
yeah sry that was kind of stupid.

**Comment by chcg** [comment]
@jeanpaulrichter I also updated the x86 version at https://npppm.bruderste.in/plugins/view/nppcrypt, thanks for correcting the appveyor release configuration.

**Comment by jeanpaulrichter** [comment]
thank you :) do you know how i force the pluginmanager to update in order to check if everything works?

**Comment by chcg** [comment]
@jeanpaulrichter X64 version is already available, you need to enable the usage of the development list under pluginmanager->show plugin manager-> settings (at the left bottom corner)

Unfortunately I had do correct the md5 sum for the x64 version.

**Comment by jeanpaulrichter** [comment]
fuck i hashed the zip not the dll :(

**Comment by chcg** [comment]
Aha. Now it is fine and the download is ok for the x64 version and plugin is working.

The handling with the web interface for x86 is much easier for this task.

**Comment by jeanpaulrichter** [comment]
yea but i like the transparency and openness of github. anyway thanks again for your help.

**Pull request merged**
