### PR TITLE
Add BetterMultiSelection plugin

### PR DESCRIPTION
**Pull request by dail8859**

### CODE REVIEW

**Comment by chcg** [comment]
@dail8859 Will you add it also for x86 or should I?

**Comment by dail8859** [comment]
@chcg I can add it. I was trying to log into the page earlier and was getting MySQL errors. Seems like I can log in now so I'll try to add it soon.

**Comment by chcg** [comment]
@dail8859 See https://github.com/chcg/BetterMultiSelection/tree/appveyor, let me know if that is of interest for you.

**Comment by dail8859** [comment]
I'll pass for now. I really don't see any further development needing done on the plugin but if I do then I'll keep your repo in mind.

**Comment by chcg** [comment]
@dail8859 Added https://npppm.bruderste.in/plugins/view/bettermultiselection

**Comment by dail8859** [comment]
@chcg Awesome thanks! You beat me to it. :)

**Pull request merged**
